import {
  Puzzle,
  SpellCheck,
  Calculator,
  FlaskConical,
  Grid3X3,
  Sparkles,
  Layers,
} from "lucide-react";
import { type KidActivity } from "@/types/activities.type";

export const kidActivities: KidActivity[] = [
  {
    id: 1,
    slug: "flashcards",
    href: "/activities/flashcards",
    title: "Flashcards Master",
    description: "Flip, learn, and remember key facts with super quick review cards.",
    icon: Grid3X3,
    color: "sky",
    duration: "10 Mins",
    badge: "AI Generated",
    xp: "+150 XP",
    steps: [
      "Choose a custom topic",
      "Flip the card to reveal answers",
      "Mark it as mastered or review",
      "Track your knowledge!",
    ],
  },
  {
    id: 2,
    slug: "quizzes",
    href: "/activities/quizzes",
    title: "Quizzes Quest",
    description: "Answer quick questions and level up with every correct choice.",
    icon: Sparkles,
    color: "green",
    duration: "5 Mins",
    badge: "AI Generated",
    xp: "+150 XP",
    steps: [
      "Choose a custom topic",
      "Pick the best answer of four",
      "Read fun feedback and facts",
      "Score 100% and win!",
    ],
  },
  {
    id: 3,
    slug: "logic-puzzles",
    href: "/activities/logic-puzzles",
    title: "Logic Puzzles",
    description: "Test your brain with tricky patterns and sequences. Great for problem solving!",
    icon: Puzzle,
    color: "sky",
    duration: "5 Mins",
    badge: "AI Generated",
    xp: "+150 XP",
    steps: [
      "Choose a custom topic",
      "Find the missing item in the sequence",
      "Click the correct emoji pattern",
      "Earn streak rewards!",
    ],
  },
  {
    id: 4,
    slug: "word-scrambles",
    href: "/activities/word-scrambles",
    title: "Word Scrambles",
    description: "Unscramble letters to find hidden words. Boost your vocabulary while playing!",
    icon: SpellCheck,
    color: "green",
    duration: "8 Mins",
    badge: "AI Generated",
    xp: "+150 XP",
    steps: [
      "Choose a custom topic",
      "Rearrange letters to spell words",
      "Use helpful clues and hints",
      "Master spelling speed!",
    ],
  },
  {
    id: 5,
    slug: "math-challenges",
    href: "/activities/math-challenges",
    title: "Math Challenges",
    description:
      "Fast-paced math fun! Solve as many as you can themed around your favorite topics.",
    icon: Calculator,
    color: "orange",
    duration: "5 Mins",
    badge: "AI Generated",
    xp: "+150 XP",
    steps: [
      "Choose a custom theme",
      "Solve math problems or word stories",
      "Select correct multiple-choice answers",
      "Train arithmetic skills!",
    ],
  },
  {
    id: 6,
    slug: "science-lab",
    href: "/activities/science-lab",
    title: "Science Lab",
    description: "Mix virtual elements and learn about the world through interactive experiments.",
    icon: FlaskConical,
    color: "purple",
    duration: "10 Mins",
    badge: "AI Generated",
    xp: "+150 XP",
    steps: [
      "Choose a custom scientific topic",
      "Answer hypotheses of experiments",
      "Discover the scientific reasons",
      "Earn laboratory stars!",
    ],
  },
  {
    id: 7,
    slug: "memory-match",
    href: "/activities/memory-match",
    title: "Memory Match",
    description: "Find the matching pairs and level up your focus and concentration.",
    icon: Grid3X3,
    color: "pink",
    duration: "5 Mins",
    badge: "Playground",
    xp: "+150 XP",
    steps: [
      "Flip over standard card tiles",
      "Match identical animal emojis",
      "Match all tiles in few flips",
      "Boost memory power!",
    ],
  },
  {
    id: 9,
    slug: "match-following",
    href: "/activities/match-following",
    title: "Match Pairs",
    description: "Draw lines and connect related items to match their correct partners.",
    icon: Layers,
    color: "orange",
    duration: "5 Mins",
    badge: "New Game",
    xp: "+150 XP",
    steps: [
      "Read the left-hand emoji prompts",
      "Find correct matches in the right grid",
      "Click matching pairs to lock bonds",
      "Complete all correct associations!",
    ],
  },
];

export const activityColorStyles: Record<KidActivity["color"], string> = {
  sky: "border-sky-500/20 bg-sky-500/10 text-sky-600",
  green: "border-green-500/20 bg-green-500/10 text-green-600",
  orange: "border-orange-500/20 bg-orange-500/10 text-orange-600",
  purple: "border-purple-500/20 bg-purple-500/10 text-purple-600",
  pink: "border-pink-500/20 bg-pink-500/10 text-pink-600",
  slate: "border-slate-500/20 bg-slate-500/10 text-slate-600",
};

export const activityButtonStyles: Record<KidActivity["color"], string> = {
  sky: "bg-sky-600 hover:bg-sky-700",
  green: "bg-green-600 hover:bg-green-700",
  orange: "bg-orange-600 hover:bg-orange-700",
  purple: "bg-purple-600 hover:bg-purple-700",
  pink: "bg-pink-600 hover:bg-pink-700",
  slate: "bg-slate-600 hover:bg-slate-700",
};
