"use server";

import { z } from "zod";
import { generateBaseActivity } from "./base-generator";

// Define the schema for a single scrambled word item generated by the AI
const aiWordScrambleItemSchema = z.object({
  answer: z
    .string()
    .describe(
      "The target word entirely in uppercase, between 1 to 20 alphabetic letters only. Absolutely no spaces, punctuation, or special characters."
    ),
  hint: z
    .string()
    .describe("A fun, exciting, and kid-friendly clue to help the child guess the word."),
});

// Define the schema for AI response
const aiWordScrambleSchema = z.object({
  words: z
    .array(aiWordScrambleItemSchema)
    .min(1)
    .describe("An array containing dynamic fun educational scrambled words."),
});

// The final schema structure that matches what database/frontend expects
const wordScrambleItemSchema = z.object({
  answer: z.string(),
  scrambled: z.string(),
  hint: z.string(),
});

export type WordScrambleActivityContent = {
  words: z.infer<typeof wordScrambleItemSchema>[];
};

/**
 * Helper to validate if a word fits the selected difficulty length constraints.
 * - easy: 3–5 letters
 * - medium: 6–8 letters
 * - hard: 9+ letters
 */
function validateDifficulty(word: string, difficulty: "easy" | "medium" | "hard"): boolean {
  const len = word.length;
  if (difficulty === "easy") {
    return len >= 3 && len <= 5;
  } else if (difficulty === "medium") {
    return len >= 6 && len <= 8;
  } else if (difficulty === "hard") {
    return len >= 9;
  }
  return false;
}

/**
 * Deterministically scramble a word:
 * - Preserves the exact letters.
 * - Always returns a different order than the original word.
 * - Output format is uppercase letters separated by spaces (e.g. "C A T" -> "A T C").
 * - Handles edge cases safely to avoid infinite loops.
 */
function scrambleWord(word: string): string {
  const letters = word.toUpperCase().split("");

  if (letters.length < 2) {
    return letters.join(" ");
  }

  // If all letters are identical (e.g., "AAA"), scrambling is impossible.
  const allIdentical = letters.every((char) => char === letters[0]);
  if (allIdentical) {
    return letters.join(" ");
  }

  const scrambled = [...letters];
  let attempts = 0;

  // Try up to 50 times to get a different permutation
  while (attempts < 50) {
    // Fisher-Yates shuffle
    for (let i = scrambled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [scrambled[i], scrambled[j]] = [scrambled[j], scrambled[i]];
    }

    if (scrambled.join("") !== word.toUpperCase()) {
      break;
    }
    attempts++;
  }

  // Fallback if shuffle failed to find a unique order
  if (scrambled.join("") === word.toUpperCase()) {
    scrambled.reverse();
    if (scrambled.join("") === word.toUpperCase()) {
      // Swap the first two different adjacent characters
      for (let i = 0; i < scrambled.length - 1; i++) {
        if (scrambled[i] !== scrambled[i + 1]) {
          [scrambled[i], scrambled[i + 1]] = [scrambled[i + 1], scrambled[i]];
          break;
        }
      }
    }
  }

  return scrambled.join(" ");
}

/**
 * Server Action to dynamically generate a dynamic spelling word scramble game
 * on a given topic for a kid user using the Vercel AI SDK and Gemini model, and save it in Supabase.
 */
export async function generateWordScramble(
  topic: string,
  count: number = 10,
  difficulty: "easy" | "medium" | "hard" = "medium"
) {
  // Strict validation of difficulty
  if (difficulty !== "easy" && difficulty !== "medium" && difficulty !== "hard") {
    return { error: "Invalid difficulty level provided." };
  }

  // Clamp word count to a safe range (1 to 20)
  const clampedCount = Math.max(1, Math.min(20, count));

  const systemPrompt = `You are an expert educational game designer and linguist who creates highly engaging learning activities for kids.
Your goal is to generate exactly ${clampedCount} unique educational words and their hints about the topic: "${topic}".

For the spelling game, every single word must fit the "${difficulty}" difficulty criteria:
- Difficulty easy: Words must be 3 to 5 letters long, simple common vocabulary, and easy hints.
- Difficulty medium: Words must be 6 to 8 letters long, grade-level vocabulary, and descriptive hints.
- Difficulty hard: Words must be 9 or more letters long, advanced vocabulary, and challenging/cognitive hints.

Strict Rules:
1. Generate EXACTLY ${clampedCount} unique words.
2. Every word's 'answer' MUST consist of uppercase A-Z letters only. No punctuation, no spaces, no special characters, no duplicate words, and no numbers.
3. Every word must be a real, valid dictionary word.
4. The 'hint' must be engaging, child-friendly, and directly related to the word.
5. All words must be highly relevant to the topic: "${topic}".
6. Do not duplicate any answers, concepts, or hints.

Before responding, internally verify that the list contains exactly ${clampedCount} unique words, they are all uppercase alphabetic characters under 20 chars long, they perfectly match the "${difficulty}" difficulty constraints, and all hints are complete.`;

  const userPrompt = `Generate exactly ${clampedCount} unique, high-quality uppercase words and hints about "${topic}" matching "${difficulty}" difficulty.`;

  return generateBaseActivity({
    topic,
    activityType: "word_scramble",
    schema: aiWordScrambleSchema,
    systemPrompt,
    userPrompt,
    maxAttempts: 3,
    validate: (object) => {
      if (!object || !Array.isArray(object.words)) {
        throw new Error("AI returned malformed or empty content.");
      }

      if (object.words.length !== clampedCount) {
        throw new Error(
          `Expected exactly ${clampedCount} words, but AI returned ${object.words.length}.`
        );
      }

      const seenAnswers = new Set<string>();

      for (const item of object.words) {
        if (!item.answer || typeof item.answer !== "string") {
          throw new Error("Word answer must be a valid string.");
        }

        const cleanAnswer = item.answer.trim().toUpperCase();

        // Uppercase alphabetic only, up to 20 characters
        if (!/^[A-Z]{1,20}$/.test(cleanAnswer)) {
          throw new Error(
            `Word '${cleanAnswer}' contains invalid characters or length. Must be 1-20 uppercase A-Z characters only.`
          );
        }

        if (seenAnswers.has(cleanAnswer)) {
          throw new Error(`Duplicate word detected: '${cleanAnswer}'. Each word must be unique.`);
        }
        seenAnswers.add(cleanAnswer);

        // Verify difficulty
        if (!validateDifficulty(cleanAnswer, difficulty)) {
          throw new Error(
            `Word '${cleanAnswer}' (length ${cleanAnswer.length}) does not match constraints for '${difficulty}' difficulty.`
          );
        }

        if (!item.hint || typeof item.hint !== "string" || item.hint.trim().length === 0) {
          throw new Error(`Word '${cleanAnswer}' has an empty or invalid hint.`);
        }
      }
    },
    transform: (object) => {
      const processedWords = object.words.map((item) => {
        const cleanAnswer = item.answer.trim().toUpperCase();
        return {
          answer: cleanAnswer,
          scrambled: scrambleWord(cleanAnswer),
          hint: item.hint.trim(),
        };
      });

      return {
        words: processedWords,
      };
    },
  });
}
