import React from "react";
import { Document, Page, Text, StyleSheet, View } from "@react-pdf/renderer";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    lineHeight: 1.6,
    fontFamily: "Helvetica",
  },

  header: {
    fontSize: 22,
    marginBottom: 20,
    color: "#0284c7",
    fontWeight: "bold",
  },

  section: {
    marginBottom: 12,
  },

  h1: {
    fontSize: 20,
    marginBottom: 10,
    marginTop: 14,
    fontWeight: "bold",
    color: "#0f172a",
  },

  h2: {
    fontSize: 16,
    marginBottom: 8,
    marginTop: 12,
    fontWeight: "bold",
    color: "#1e293b",
  },

  h3: {
    fontSize: 14,
    marginBottom: 6,
    marginTop: 10,
    fontWeight: "bold",
    color: "#334155",
  },

  text: {
    fontSize: 12,
    color: "#334155",
    marginBottom: 8,
  },

  bold: {
    fontWeight: "bold",
  },

  bulletRow: {
    flexDirection: "row",
    marginBottom: 6,
    alignItems: "flex-start",
  },

  bullet: {
    width: 14,
    fontSize: 12,
  },

  bulletText: {
    flex: 1,
    fontSize: 12,
    color: "#334155",
  },

  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 10,
    color: "#94a3b8",
  },
});

const cleanMarkdown = (content: string) => {
  return content
    .replace(/\r/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
};

const emojiRegex = /\p{Emoji_Presentation}|\p{Extended_Pictographic}/gu;

const renderTextWithEmoji = (children: React.ReactNode) => {
  const processNode = (node: React.ReactNode): React.ReactNode => {
    if (typeof node === "string") {
      const parts = node.split(emojiRegex);
      const emojis = node.match(emojiRegex) || [];

      const result: React.ReactNode[] = [];

      parts.forEach((part, index) => {
        if (part) {
          result.push(
            <Text key={`text-${index}`} style={{ fontFamily: "NotoSans" }}>
              {part}
            </Text>
          );
        }

        if (emojis[index]) {
          result.push(
            <Text key={`emoji-${index}`} style={{ fontFamily: "NotoEmoji" }}>
              {emojis[index]}
            </Text>
          );
        }
      });

      return result;
    }

    if (Array.isArray(node)) {
      return node.map((child, index) => (
        <React.Fragment key={index}>{processNode(child)}</React.Fragment>
      ));
    }

    return node;
  };

  return processNode(children);
};

const MarkdownToPdf = ({ content }: { content: string }) => {
  const cleanedContent = cleanMarkdown(content);

  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        h1: ({ children }) => <Text style={styles.h1}>{renderTextWithEmoji(children)}</Text>,

        h2: ({ children }) => <Text style={styles.h2}>{renderTextWithEmoji(children)}</Text>,

        h3: ({ children }) => <Text style={styles.h3}>{renderTextWithEmoji(children)}</Text>,

        p: ({ children }) => <Text style={styles.text}>{renderTextWithEmoji(children)}</Text>,

        strong: ({ children }) => <Text style={styles.bold}>{renderTextWithEmoji(children)}</Text>,

        li: ({ children }) => (
          <View style={styles.bulletRow} wrap={false}>
            <Text style={styles.bullet}>•</Text>
            <Text style={styles.bulletText}>{renderTextWithEmoji(children)}</Text>
          </View>
        ),
      }}
    >
      {cleanedContent}
    </ReactMarkdown>
  );
};

type PdfDocumentProps = {
  content: string;
};

export const PdfDocument = ({ content }: PdfDocumentProps) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>
          Learning Material <Text style={{ fontFamily: "NotoEmoji" }}>📘</Text>
        </Text>

        <View style={styles.section}>
          <MarkdownToPdf content={content} />
        </View>

        <Text style={styles.footer}>Generated by ChatGPT Kids</Text>
      </Page>
    </Document>
  );
};
